config/routes.rb
Rails.application.routes.draw do
 
  resources :users do
    resources :sessions do
      resources :records
      resources :tracks
    end
  end

  root "users#index"

end

app/models/session.rb
class Session < ActiveRecord::Base
    belongs_to :user
    has_many :tracks

    validates :session_name, presence: true
    validates :description, presence: true
    validates :description, length: {maximum: 300}
    validates :session_name, length: {minimum: 7}
    validates :session_name, length: {maximum: 50}
    validates :user_id, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
    belongs_to :session
    has_attached_file :audio
    validates_attachment_presence :audio
    validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg', 'audio/wav']
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
         @user = User.find(params[:user_id]) 
         @session = @user.sessions.all
         @tracks = Track.all
    end
    #sessions#show redirigir a esta ruta al pinchar sobre la session
    def show
        @user = User.find(params[:user_id]) 
        @session = @user.sessions.find(params[:id])
        @tracks = Track.all
    end

    def new
        @user = User.find(params[:user_id]) 
        @session = @user.sessions.new 
        @tracks = Track.all
    end

    def create
        @user = User.find(params[:user_id]) 
        @session = @user.sessions.new sessions_params
        @tracks = Track.new 
                                                 
        if @session.save 
            flash[:notice] = "You have created a new session"
            redirect_to edit_user_session_path(@user, @session)
        else
            flash[:error] = "You could not create a new session"
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:user_id])
        @session = Session.find(params[:id])
        if @session == nil
            render 'sessions/index'
        end
    end

    def update
        @user = User.find(params[:user_id])
        @session = Session.find(params[:id])
        @tracks = Track.all
       
        
        if @session.update_attributes sessions_params
            redirect_to user_sessions_path
        else
            @errors = @session.errors.full_messages
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        @session = Session.destroy(params[:id])
        redirect_to user_sessions_path(@user)
    end

    private
    def sessions_params
        params.require(:session).permit(:session_name, :description, :user_id) 
    end 
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @user = User.find(params[:user_id]) 
    @session = @user.sessions.find(params[:session_id])
    @track = Track.new
  end
  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @user = User.find(params[:user_id]) 
    @session = @user.sessions.find(params[:session_id])
    @track = @session.tracks.new(track_params)
    respond_to do |format|
      if @track.save
        format.html { redirect_to edit_user_session_path(@user, @session), notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @user = User.find(params[:user_id]) 
    @session = @user.sessions.find(params[:session_id])
    @track = @session.tracks.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_session_path(@user, @session), notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:audio, :name)
    end
  
end

app/controllers/users_controller.rb
require 'services/highlights'
class UsersController < ApplicationController
    def initialize(*args)
        super(*args)
        @highlightService = Services::Highlights.new();   
    end

    def index
    end

    def show                
        @user = User.find(params[:id])
        @users = User.all
        @session = @user.sessions.find(params[:id])
        @tracks = Track.all
        @highlights = @highlightService.getHighestRankedSessions()
    end
    
    private
    def sessions_params
        params.require(:session).permit(:session_name, :description, :user_id) 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundLink</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', :defer => "defer" %>
  <%= javascript_include_tag "//cdn.webrtc-experiment.com/RecordRTC.js", :defer => "defer" %>
  <%= javascript_include_tag '//cdn.webrtc-experiment.com/ffmpeg_asm.js', :defer => "defer" %>
  <%= csrf_meta_tags %>
</head>
<body>
    
<%= yield %>

</body>
</html>

app/views/tracks/_form.html.erb
<%= form_for [@user, @session, @track] do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> This file can not be saved</h2>

      <ul>
        <% @track.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Track name' %><br>
    <%= f.text_field :name %>
    <% f.label :audio %><br>
    <%= f.file_field :audio %>
  </div>
  <div class="actions">
    <%= f.submit 'Add track', :class => 'button' %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>
  <p>Audio tracks</p>


<table>
    <% @tracks.each do |track| %>
      <tr>
        <td><audio id='<%= session.id %>' class="player" src='<%= track.audio %>' controls></audio></td>
        <td><%= track.name %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Delete', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<header class='SoundLink'>
    <h2>NEW TRACK</h2>
    <p >Sound-Link</p>
</header>
<section id='session'>
    <%= render 'form' %>

    <%= link_to 'Back', edit_user_session_path(@user, @session), :class => 'title' %>
</section>
<footer>
    <div class='title'><h3>by Franx0</h3></div>
</footer>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Audio:</strong>
  <%= @track.name %>
</p>

<audio id='<%= session.id %>' class="player" src='<%= @track.audio %>' controls></audio>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>

app/views/users/index.html.erb
<header class='SoundLink'>
    <p style='line-height: 80px;'>Welcome to Sound-Link</p>
</header>
<!--
<div id="divBackground"></div>
  <span id="status">Waiting to connect</span>
  <div id="dlgLogin" class="ui-widget">
  </div>

  <iframe id="dlgOauth" class="ui-widget"></iframe>

    Call<br /> <input type="text" id="destination" placeholder="Destination" />

  <div id="dlgChat" class="ui-widget">
    <audio id="audRemote"></audio>
    <p align="center">
      <video id="vidRemote" width="320" height="240"
        poster="img/poster.jpg" autoplay="autoplay"></video>
    </p>
    <p align="center">
      <video id="vidLocal" width="160" height="120"
        poster="img/poster.jpg" autoplay="autoplay"></video>
    </p>
  </div>

  <div id="dlgError" class="ui-widget ui-front">
    <p id="pErrorMessage" class="ui-state-error ui-corner-all"
      style="padding: 0.5em;">
      <span class="ui-icon ui-icon-alert"
        style="float: left; margin-right: 0.5ex;"></span>
      <span id="spnErrorMessage"
        style="display: block; overflow: hidden"></span>
    </p>
  </div>

  <img id="imgSpinner" src="img/ajax-loader.gif" height="32" width="32"
    class="ui-helper-hidden">
  <audio id="audRing" src="/common/audio/uk-ringtone.wav" preload="auto" loop></audio> 
<input type="button" id="user1" value="User1 button">
<input type="button" id="user2" value="User2 button"></br>
<input type="button" id="call" value="call">
<input type="button" id="disconnect" value="disconnect">
-->
<div id="divBackground"></div>

<span id="status">Waiting to connect</span>
    <div id="dlgLogin" class="ui-widget"></div>
  <input type="button" id="dlgLogin1" class="ui-widget" value="user1">

  <input type="button" id="dlgLogin2" class="ui-widget" value="user2">

  <iframe id="dlgOauth" class="ui-widget"></iframe>

  <input type="button" id="dlgSelectUser" class="ui-widget" value="call">
  <input type="button" id="dlgDisconnect" class="ui-widget" value="disconnect">
    <p>
      Call<br /> <input type="text" id="txtChatWith" />
    </p>

  <div id="dlgChat" class="ui-widget">
    <audio id="audRemote"></audio>
    <p align="center">
      <video id="vidRemote" width="320" height="240"
        poster="img/poster.jpg" autoplay="autoplay"></video>
    </p>
    <p align="center">
      <video id="vidLocal" width="160" height="120"
        poster="img/poster.jpg" autoplay="autoplay"></video>
    </p>
  </div>

  <div id="dlgError" class="ui-widget ui-front">
    <p id="pErrorMessage" class="ui-state-error ui-corner-all"
      style="padding: 0.5em;">
      <span class="ui-icon ui-icon-alert"
        style="float: left; margin-right: 0.5ex;"></span>
      <span id="spnErrorMessage"
        style="display: block; overflow: hidden"></span>
    </p>
  </div>

  <img id="imgSpinner" src="img/ajax-loader.gif" height="32" width="32"
    class="ui-helper-hidden">
  <audio id="audRing" src="/common/audio/uk-ringtone.wav" preload="auto" loop></audio> 

app/views/users/show.html.erb
<header class='SoundLink'>
    <h2>Welcome <%= @user.user_name %></h2>
    <p>Sound-Link</p>
</header>

<div class='title'>
    <h1>Your last sessions</h1>
</div>

<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<h2><%= link_to "Go to your sessions!", user_sessions_path(@user), :class => 'title' %></h2>

<section id='session'>
    <h3><%= @user.sessions.last.session_name %></h3>
    <div id='description'>
        <p><%= @user.sessions.last.description %></p>
    </div>

    <% @user.sessions.last.tracks.each do |track| %>
        <ul>
            <% if track.audio_content_type!=nil %>
                <li>
                    <p class='trackname'><%= track.audio_file_name %></p>
                    <audio id='<%= session.id %>' class="player" src='<%= track.audio %>' controls></audio>
            <% else %>
                <p>This session doesn't contain any track!</p>
            <% end %>
        </ul>
    <% end %>
    <div id='<%= session.id %>' class='btn-play button'>Play session</div>
    <div id='<%= session.id %>' class='btn-pause button'>Pause session</div>
    <div id='<%= session.id %>' class='btn-stop button'>Stop session</div>
</section>

<div class='title'>
    <h1>Recent users sessions</h1>
</div>

<aside id='openSession'>
<% @highlights.each do |session| %>
    <section id='session'>
        <% user = session.user %>
        <h3><%= user.nickname %></h3>
        <h3><%= session.session_name %></h3>
        <div id='description'>
            <p><%= session.description %></p>
        </div>
        <ul>
            <% @session.tracks.each do |track| %>
                <% if track.audio_content_type!=nil %>
                    <li>
                        <p class='trackname'><%= track.audio_file_name %></p>
                        <audio id='<%= session.id %>' class="player" src='<%= track.audio %>' controls></audio>
                        <input id='<%= session.id %>' class="time" type="number" value=0>seg.</input>
                <% else %>
                    <p>There isn't any record in your session</p>
                <% end %>
            <% end %>
        </ul>
        <div id='<%= session.id %>' class='btn-play button'>Play session</div>
        <div id='<%= session.id %>' class='btn-pause button'>Pause session</div>
        <div id='<%= session.id %>' class='btn-stop button'>Stop session</div>
<div id='links'>
        <br><%= link_to 'Edit', edit_user_session_path(@user, session) %>
        <br><%= link_to 'Remove session', user_session_path(@user, session), method: :delete, data: {confirm: "Are you sure?"} %>
    </section>
<% end %>
</aside>
<footer>
    <div class='title'><h3>by Franx0</h3></div>
</footer>

